# docker-compose.yml
services:
  db:
    image: postgis/postgis:15-3.3  # Use the PostGIS image
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-myuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-mypassword}"
      POSTGRES_DB: "${POSTGRES_DB:-mydb}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: my_streamlit_app
    restart: always
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: "${POSTGRES_USER:-myuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-mypassword}"
      POSTGRES_DB: "${POSTGRES_DB:-mydb}"
    depends_on:
      - db

volumes:
  postgres_data:
